(() => {
  'use strict';
  let lastLive = null, lastCover = null;
  let coverVideos = [], coverIndex = 0;
  const $ = id => document.getElementById(id);

  async function json(path, signal){const r=await fetch(path,{signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
  function hhmm(iso){return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso));}
  function renderLive(heading, streams){$('live-heading').textContent=heading||'AI Picks';$('live-list').replaceChildren(...streams.map(s=>{const d=document.createElement('div');d.className='card';d.textContent=`${hhmm(s.scheduled_start)}  ${s.title} — ${s.channel_title}`;return d;}));$('live-picks').hidden=false;}
  function updatePlayer(){if(!coverVideos.length)return;const v=coverVideos[coverIndex];$('cover-player').src=`https://www.youtube.com/embed/${encodeURIComponent(v.video_id)}?rel=0&playsinline=1`;$('cover-player-label').textContent=`${coverIndex+1} / ${coverVideos.length}  ${v.title||v.channel_title}`;}
  function renderCover(heading,songs){$('cover-heading').textContent=heading||'AI Cover Picks';const cards=[];coverVideos=[];for(const s of songs){const v=(s.playlist_videos||[])[0];if(v)coverVideos.push(v);const d=document.createElement('div');d.className='card';const charts=s.charts||{};d.innerHTML=`<div class="title"></div><div class="muted artist"></div><div class="metric"></div>`;d.querySelector('.title').textContent=s.title;d.querySelector('.artist').textContent=s.artists||'';d.querySelector('.metric').textContent=`Demand ${Math.round(s.chart_demand_score||0)}/100 · recent covers ${s.recent_cover_count??'—'} · weekly ${charts.weekly??'—'}`;cards.push(d);}$('cover-list').replaceChildren(...cards);$('cover-picks').hidden=false;$('cover-player-area').hidden=!coverVideos.length;coverIndex=0;if(coverVideos.length)updatePlayer();}
  $('cover-prev').onclick=()=>{if(coverVideos.length){coverIndex=(coverIndex-1+coverVideos.length)%coverVideos.length;updatePlayer();}};
  $('cover-next').onclick=()=>{if(coverVideos.length){coverIndex=(coverIndex+1)%coverVideos.length;updatePlayer();}};

  async function register(){
    if(!document.modelContext?.registerTool){console.info('[TubeSaku demo] WebMCP unavailable.');return;}
    await document.modelContext.registerTool({name:'search_live_streams',title:'Search TubeSaku sample live streams',description:'Search sample Japanese YouTube live schedule data. Preserve original titles.',inputSchema:{type:'object',properties:{keyword:{type:'string'},debut_only:{type:'boolean'},limit:{type:'integer',minimum:1,maximum:30,default:20}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input={},ctx={})=>{const data=await json('./sample-streams.json',ctx.signal);const q=(input.keyword||'').toLowerCase();let rows=(data.streams||[]).filter(s=>(!input.debut_only||s.is_debut_candidate)&&(!q||`${s.title} ${s.channel_title}`.toLowerCase().includes(q))).slice(0,input.limit||20);lastLive={streams:rows};return lastLive;}});
    await document.modelContext.registerTool({name:'show_live_streams',title:'Show selected streams on TubeSaku demo',description:'Render IDs from the latest live search into the page.',inputSchema:{type:'object',properties:{video_ids:{type:'array',minItems:1,maxItems:10,items:{type:'string'}},heading:{type:'string'}},required:['video_ids'],additionalProperties:false},execute:async({video_ids,heading})=>{if(!lastLive)throw new Error('Run search_live_streams first.');const m=new Map(lastLive.streams.map(s=>[s.video_id,s]));const selected=video_ids.map(id=>m.get(id)).filter(Boolean);renderLive(heading,selected);return{success:true,displayed_count:selected.length};}});
    await document.modelContext.registerTool({name:'search_cover_songs',title:'Search TubeSaku sample cover-song opportunities',description:'Compare Japanese song demand, recent cover supply and playable examples.',inputSchema:{type:'object',properties:{scope:{type:'string',enum:['all','low_supply','top_demand'],default:'all'},limit:{type:'integer',minimum:1,maximum:20,default:10}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input={},ctx={})=>{const data=await json('./sample-cover-songs.json',ctx.signal);let rows=data.songs||[];if(input.scope==='low_supply')rows=rows.filter(s=>(s.recent_cover_count??99)<=2);if(input.scope==='top_demand')rows=[...rows].sort((a,b)=>(b.chart_demand_score||0)-(a.chart_demand_score||0));rows=rows.slice(0,input.limit||10);lastCover={songs:rows};return lastCover;}});
    await document.modelContext.registerTool({name:'show_cover_playlist',title:'Show an AI-selected cover playlist',description:'Render songs from the latest cover search and build an in-page YouTube listening shortlist.',inputSchema:{type:'object',properties:{song_ids:{type:'array',minItems:1,maxItems:10,items:{type:'string'}},heading:{type:'string'}},required:['song_ids'],additionalProperties:false},execute:async({song_ids,heading})=>{if(!lastCover)throw new Error('Run search_cover_songs first.');const m=new Map(lastCover.songs.map(s=>[s.song_id,s]));const selected=song_ids.map(id=>m.get(id)).filter(Boolean);renderCover(heading,selected);return{success:true,displayed_count:selected.length};}});
    console.info('[TubeSaku demo] 4 WebMCP tools registered.');
  }
  register().catch(console.error);
})();
